apiVersion: v1
kind: Service
metadata:
  name: branch
  labels:
    svc: testapi
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8887"
spec:
  ports:
    - name: query
      port: 8888
      protocol: TCP
    - name: metrics
      port: 8887
      protocol: TCP
  selector:
    run: branch
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    run: branch
  name: branch
spec:
  replicas: 1
  selector:
    matchLabels:
      run: branch
  template:
    metadata:
      labels:
        run: branch
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - branch
              topologyKey: "kubernetes.io/hostname"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: run
                    operator: In
                    values:
                      - root
                      - leaf
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: config
          configMap:
            name: stresscfg
      containers:
        - name: branch
          resources:
            limits:
              memory: "2048Mi"
              cpu: "4"
          env:
            - name: UPSTREAM_URI
              value: 0.0.0.0:8888
            - name: DOWNSTREAM_URI
              value: http://leaf:8888
            - name: REPORTER_URI
              value: http://zipkin:9411/api/v2/spans
            - name: SERVICE_NAME
              value: branch
            - name: PRIME_MAX
              value: "100000"
            - name: JOBFILE
              value: /etc/testapi/config/stress.cfg
          image: mcastelino/test-api-server:latest
          volumeMounts:
            - name: config
              mountPath: /etc/testapi/config
